# Generated by Django 5.1.2 on 2024-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="header",
            field=models.ImageField(upload_to="headers/"),
        ),
    ]
