# Generated by Django 5.1.2 on 2024-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_avatar_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="placeholders/avatar_placeholder.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="header",
            field=models.ImageField(
                default="placeholders/header_placeholder.png", upload_to="headers/"
            ),
        ),
    ]
